---

- name: install packer
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ PACKER_VERSION }}/packer_{{ PACKER_VERSION }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: True

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ TERRAFORM_VERSION }}/terraform_{{ TERRAFORM_VERSION }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: True

- name: cleanup
  file: path=/usr/local/terraform state=absent