---

- name: download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ TERRAFORM_VERSION }}/terraform_{{ TERRAFORM_VERSION }}_linux_amd64.zip
    dest: /tmp/terraform_{{ TERRAFORM_VERSION }}_linux_amd64.zip

- name: download packer
  get_url:
    url: https://releases.hashicorp.com/packer/{{ PACKER_VERSION }}/packer_{{ PACKER_VERSION }}_linux_amd64.zip
    dest: /tmp/packer_{{ PACKER_VERSION }}_linux_amd64.zip

- name: install terraform
  unarchive:
    src: /tmp/terraform_{{ TERRAFORM_VERSION }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    copy: yes

- name: install terraform
  unarchive:
    src: /tmp/packer_{{ PACKER_VERSION }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    copy: yes

- name: cleanup
  file: path=/usr/local/terraform state=absent